rules:
  rule1:
    source_rooms: ["!roomid:example.com", "!roomid2:example.com"]
    target_room: "!t_roomid:example.com"
    users: ["@user:example.com"]
    reaction: "ğŸ‘€"
  rule2:
    source_rooms: ["!roomid2:example.com"]
    target_room: "!t_roomid2:example.com"
    reaction: "â­ï¸"
